name: APK Live Cam Premium

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar Cordova y Construir
      run: |
        npm install -g cordova
        
        cordova create app_temp com.usuario.livecam "Live Cam Pro"
        cd app_temp
        
        # --- PLUGINS ---
        cordova plugin add cordova-plugin-camera
        cordova plugin add cordova-plugin-android-permissions
        
        # Plugins para el Look & Feel (Barras de estado y navegación)
        cordova plugin add cordova-plugin-statusbar
        cordova plugin add cordova-plugin-navigationbar-color

        # --- PREPARAR ARCHIVOS ---
        rm config.xml
        rm -rf www/*
        
        cp ../config.xml .
        cp ../index.html www/
        
        cordova platform add android
        
        cordova build android --debug

    - name: Subir APK
      uses: actions/upload-artifact@v4
      with:
        name: live-cam-premium
        path: app_temp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
